import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const fnum = (v) => (Number.isInteger(v) ? `${v}.f` : `${v}f`);

export function generateInc(data) {
  const lines = [
    "// AUTO-GENERATED by host/scripts/gen-cries.mjs from host/seed/species-cries.json",
    "// Do not edit by hand. Regenerate: cd host && node scripts/gen-cries.mjs",
    `#define SND_SPECIES_BASE ${data.soundBase}`,
    `#define SND_SPECIES_COUNT ${data.species.length}`,
    "",
  ];
  data.species.forEach((s, i) => {
    const notes = s.notes.map((n) => `{${fnum(n.f0)}, ${fnum(n.f1)}, ${n.ms}}`).join(", ");
    lines.push(`static const Note SPECIES_CRY_${i}[] = { ${notes} }; // ${s.key} -> sound id ${data.soundBase + i}`);
  });
  lines.push("", "struct SpeciesCry { const Note *notes; int count; };",
    "static const SpeciesCry SPECIES_CRIES[SND_SPECIES_COUNT] = {");
  data.species.forEach((s, i) => lines.push(`  { SPECIES_CRY_${i}, ${s.notes.length} }, // ${s.key}`));
  lines.push("};", "");
  return lines.join("\n");
}

const isCli = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isCli) {
  const data = JSON.parse(
    readFileSync(fileURLToPath(new URL("../seed/species-cries.json", import.meta.url)), "utf8"));
  const out = fileURLToPath(new URL("../../firmware/main/species_cries.inc", import.meta.url));
  writeFileSync(out, generateInc(data));
  console.log(`wrote ${out}`);
}
